version: '3.8'

services:
  builder:
    image: archlinux:latest
    volumes:
      - ../release:/release:rw
      - .:/pkg:ro
      - ../..:/src:ro
    command: >
      bash -c "
        echo Building wikiman-${PKGVER}-${PKGREL} for Arch Linux... &&
        pacman -Sy --noconfirm git make binutils fakeroot &&
        git clone https://aur.archlinux.org/wikiman.git &&
        useradd -u ${UID} builder &&
        chown builder:builder ./wikiman &&
        cd ./wikiman &&
        su builder -c 'makepkg -d' &&
        mv wikiman-${PKGVER}-${PKGREL}-any.pkg.tar.xz /release &&
        chown ${UID}:${UID} /release/wikiman-${PKGVER}-${PKGREL}-any.pkg.tar.xz &&
        echo Build completed successfully!
      "
