version: '3.8'

services:
  builder:
    image: fedora:latest
    volumes:
      - ../release:/release:rw
      - .:/pkg:ro
      - ../..:/src:ro
    command: >
      bash -c "
        echo Building wikiman-${PKGVER}-${PKGREL} for Fedora... &&
        echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf &&
        dnf install -y rpm-build make &&
        mkdir -p ~/rpmbuild/SOURCES &&
        mkdir -p ~/rpmbuild/SPECS &&
        cp -arp /src ~/wikiman &&
        cd ~/wikiman &&
        make package &&
        tar czf ~/rpmbuild/SOURCES/${PKGVER}.tar.gz ./pkgbuild &&
        sed 's|BUILDER_PKGVER|${PKGVER}|g; s|BUILDER_PKGREL|${PKGREL}|g' /pkg/.spec > ~/rpmbuild/SPECS/wikiman.spec &&
        rpmbuild -bb ~/rpmbuild/SPECS/wikiman.spec &&
        mv ~/rpmbuild/RPMS/noarch/wikiman-${PKGVER}-${PKGREL}.fc32.noarch.rpm /release &&
        chown ${UID}:${UID} /release/wikiman-${PKGVER}-${PKGREL}.fc32.noarch.rpm &&
        echo Build completed successfully!
      "