name: Packager

on:
  release:
    types:
      - created

jobs:
  # arch:
  #   name: Arch Linux
  #   runs-on: ubuntu-latest
  #   container: archlinux/base

  #   steps:
  #   - uses: actions/checkout@v2.3.2
  #   - name: Prepare system
  #     id: prepare
  #     run: |
  #       pacman -Sy --noconfirm git make binutils fakeroot nodejs npm
  #       rm -rf ~/aur ~/release
  #       mkdir -p ~/release

  #   - name: Clone AUR package git repository
  #     id: clone_aur
  #     run: |
  #       git clone https://aur.archlinux.org/wikiman.git

  #   - name: Build package
  #     id: build
  #     run: |    
  #       useradd builder
  #       ~/aur/clean.sh
  #       chown builder:builder ~/aur
  #       cd ~/aur
  #       su builder -c 'makepkg -d'
  #       mv ./wikiman-*.pkg.* ~/release

  #   - name: Test installation
  #     id: test
  #     run: |
  #       pacman -U --noconfirm ~/release/wikiman-*.pkg*

  #   - name: Upload package to release
  #     id: upload
  #     uses: svenstaro/upload-release-action@2.1.0
  #     with:
  #       repo_token: ${{ secrets.GITHUB_TOKEN }}
  #       file: ~/release/wikiman-${{ github.ref }}-1_any.deb
  #       asset_name: wikiman-${{ github.ref }}-1_any.deb
  #       tag: ${{ github.ref }}
  #       overwrite: true

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:

    - name: Prepare system
      id: prepare
      run: |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/Europe/Belgrade /etc/localtime
        apt update
        apt -y install make nodejs
        dpkg-reconfigure --frontend noninteractive tzdata
        mkdir -p ~/release

    - name: Compile package
      id: compile
      run: |
        if [[ "${{github.ref}}" =~ ^refs ]]; then
          version="2.r$(echo '${{github.sha}}' | cut -c 1-7)-git"
        else
          version="${{github.ref}}"
        fi
        make all
        mkdir -p ./pkgbuild/DEBIAN
        cp ./pkg/deb/conffiles ./pkgbuild/DEBIAN
        sed "s|BUILDER_PKGVER|$version|g" ./pkg/deb/control > ./pkgbuild/DEBIAN/control

    - name: Build package
      id: build
      run: |
        if [[ "${{github.ref}}" =~ ^refs ]]; then
          version="2.r$(echo '${{github.sha}}' | cut -c 1-7)-git"
        else
          version="${{github.ref}}"
        fi
        dpkg -b ./pkgbuild "wikiman-${version}-1_any.deb"
        mv "wikiman-${version}-1_any.deb" ~/release

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ~/release/wikiman-${{ github.ref }}-1_any.deb
        asset_name: wikiman-${{ github.ref }}-1_any.deb
        tag: ${{ github.ref }}
        overwrite: true

  # fedora:
  #   name: Fedora
  #   runs-on: ubuntu-latest
  #   container: fedora:latest
  #   steps:

  #   - name: Prepare system
  #     id: prepare
  #     run: |
  #       echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
  #       dnf install -y rpm-build make
  #       mkdir -p ~/rpmbuild/SOURCES
  #       mkdir -p ~/rpmbuild/SPECS
  #       mkdir -p ~/release

  #   - name: Compile package
  #     id: compile
  #     run: |
  #       if [[ "${{github.ref}}" =~ ^refs ]]; then
  #         version="2.r$(echo '${{github.sha}}' | cut -c 1-7)-git"
  #       else
  #         version="${{github.ref}}"
  #       fi
  #       make
  #       tar czf "$version.tar.gz" ./pkgbuild
  #       mv "$version.tar.gz" ~/rpmbuild/SOURCES
  #       cp ./pkg/rpm/.spec ~/rpmbuild/SPECS/wikiman.spec
  #       sed "s|BUILDER_PKGVER|$version|g; s|BUILDER_PKGREL|1|g" -i ~/rpmbuild/SPECS/wikiman.spec
  #       cat ~/rpmbuild/SPECS/wikiman.spec

  #   - name: Build package
  #     id: build
  #     run: |
  #       if [[ "${{github.ref}}" =~ ^refs ]]; then
  #         version="2.r$(echo '${{github.sha}}' | cut -c 1-7)-git"
  #       else
  #         version="${{github.ref}}"
  #       fi
  #       rpmbuild -bb ./pkg/rpm/.spec
  #       mv ~/rpmbuild/RPMS/noarch/wikiman-$version-1.fc32.noarch.rpm ~/release