name: Packager

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

jobs:

  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Prepare system
      id: prepare
      run: |
        pacman -Syu --noconfirm make binutils fakeroot nodejs npm curl

    - name: Prepare source package
      id: package
      run: |
        curl -LOs https://github.com/filiparag/wikiman/archive/${GITHUB_REF#refs/*/}.tar.gz
        echo "pkgver=${GITHUB_REF#refs/*/}" > PKGBUILD
        echo "pkgrel=1" >> PKGBUILD
        echo "sha256sums=('$hashsum')" >> PKGBUILD
        echo "source=("${GITHUB_REF#refs/*/}.tar.gz")" >> PKGBUILD
        curl 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=wikiman' -so PKGBUILD.original
        sed '/^pkgver=/d; /^pkgrel=/d; /^source=/d; /^sha256sums=/d' -i PKGBUILD.original
        cat PKGBUILD.original >> PKGBUILD

    - name: Build package
      id: build
      run: |    
        useradd builder
        chown -R builder:builder .
        su builder -c 'makepkg --printsrcinfo > .SRCINFO'
        su builder -c 'makepkg -d'
        mv ./wikiman-*.pkg.* wikiman-${GITHUB_REF#refs/*/}-1-any.pkg.tar.xz

    - name: Test installation
      id: test
      run: |
        pacman -U --noconfirm wikiman-${GITHUB_REF#refs/*/}-1-any.pkg.tar.xz

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wikiman-${GITHUB_REF#refs/*/}-1-any.pkg.tar.xz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: false

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:

    - name: Prepare system
      id: prepare
      run: |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/Europe/Belgrade /etc/localtime
        apt update
        apt -y install make nodejs curl
        dpkg-reconfigure --frontend noninteractive tzdata

    - name: Prepare source package
      id: package
      run: |
        curl -LOs https://github.com/filiparag/wikiman/archive/${GITHUB_REF#refs/*/}.tar.gz
        tar zxf ${GITHUB_REF#refs/*/}.tar.gz

    - name: Compile package
      id: compile
      run: |
        make -f wikiman-${GITHUB_REF#refs/*/}/Makefile
        mkdir -p wikiman-${GITHUB_REF#refs/*/}/pkgbuild/DEBIAN
        cp wikiman-${GITHUB_REF#refs/*/}/pkg/deb/conffiles wikiman-${GITHUB_REF#refs/*/}/pkgbuild/DEBIAN
        cp wikiman-${GITHUB_REF#refs/*/}/pkg/deb/control wikiman-${GITHUB_REF#refs/*/}/pkgbuild/DEBIAN
        sed "s|BUILDER_PKGVER|${GITHUB_REF#refs/*/}|g" wikiman-${GITHUB_REF#refs/*/}/pkgbuild/DEBIAN/control

    - name: Build package
      id: build
      run: |
        dpkg -b wikiman-${GITHUB_REF#refs/*/}/pkgbuild wikiman-${GITHUB_REF#refs/*/}-1_any.deb

    - name: Test installation
      id: test
      run: |
        apt -y install man fzf ripgrep gawk w3m
        dpkg -i wikiman-${GITHUB_REF#refs/*/}-1_any.deb

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wikiman-${GITHUB_REF#refs/*/}-1_any.deb
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: false

  fedora:
    name: Fedora
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:

    - name: Prepare system
      id: prepare
      run: |
        dnf install -y rpm-build make nodejs curl
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
    
    - name: Prepare source package
      id: package
      run: |
        curl -LOs https://github.com/filiparag/wikiman/archive/${GITHUB_REF#refs/*/}.tar.gz
        tar zxf ${GITHUB_REF#refs/*/}.tar.gz
        cp wikiman-${GITHUB_REF#refs/*/}/pkg/rpm/.spec ~/rpmbuild/SPECS/wikiman.spec
        mv "${GITHUB_REF#refs/*/}.tar.gz" ~/rpmbuild/SOURCES

    - name: Build package
      id: build
      run: |
        export PKGVER="${GITHUB_REF#refs/*/}"
        export PKGREL="1"
        rpmbuild -bb ~/rpmbuild/SPECS/wikiman.spec
        mv ~/rpmbuild/RPMS/noarch/wikiman-*.rpm wikiman-${GITHUB_REF#refs/*/}-1.noarch.rpm

    - name: Test installation
      id: test
      run: |
        dnf install -y wikiman-${GITHUB_REF#refs/*/}-1.noarch.rpm

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wikiman-${GITHUB_REF#refs/*/}-1.noarch.rpm
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: false