name: Packager

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

jobs:

  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Prepare system
      id: prepare
      run: |
        pacman -Sy --noconfirm make binutils fakeroot nodejs npm curl
        rm -rf ~/build ~/release
        mkdir -p ~/release ~/build

    - name: Prepare source package
      id: package
      run: |
        mkdir -p ~/wikiman-${GITHUB_REF#refs/*/}
        cp -r * ~/wikiman-${GITHUB_REF#refs/*/}
        cd ~
        tar czf "${GITHUB_REF#refs/*/}.tar.gz" wikiman-${GITHUB_REF#refs/*/}
        hashsum="$(sha256sum "${GITHUB_REF#refs/*/}.tar.gz" | cut -d' ' -f1)"
        mv "${GITHUB_REF#refs/*/}.tar.gz" ~/build
        echo "pkgver=${GITHUB_REF#refs/*/}" > ~/build/PKGBUILD
        echo "pkgrel=1" >> ~/build/PKGBUILD
        echo "sha256sums=('$hashsum')" >> ~/build/PKGBUILD
        echo "source=("${GITHUB_REF#refs/*/}.tar.gz")" >> ~/build/PKGBUILD
        curl 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=wikiman' -so ~/build/PKGBUILD.original
        sed '/^pkgver=/d; /^pkgrel=/d; /^source=/d; /^sha256sums=/d' -i ~/build/PKGBUILD.original
        cat ~/build/PKGBUILD.original >> ~/build/PKGBUILD

    - name: Build package
      id: build
      run: |    
        useradd builder
        chown -R builder:builder ~/build
        cd ~/build
        su builder -c 'makepkg --printsrcinfo > .SRCINFO'
        su builder -c 'makepkg -d'
        mv ./wikiman-*.pkg.* ~/release

    - name: Test installation
      id: test
      run: |
        pacman -U --noconfirm ~/release/wikiman-*.pkg*

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ~/release/wikiman-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:

    - name: Prepare system
      id: prepare
      run: |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/Europe/Belgrade /etc/localtime
        apt update
        apt -y install make nodejs
        dpkg-reconfigure --frontend noninteractive tzdata
        rm -rf ~/release
        mkdir -p ~/release

    - name: Compile package
      id: compile
      run: |
        make all
        mkdir -p ./pkgbuild/DEBIAN
        cp ./pkg/deb/conffiles ./pkgbuild/DEBIAN
        sed "s|BUILDER_PKGVER|${GITHUB_REF#refs/*/}|g" ./pkg/deb/control > ./pkgbuild/DEBIAN/control

    - name: Build package
      id: build
      run: |
        dpkg -b ./pkgbuild "wikiman-${GITHUB_REF#refs/*/}-1_any.deb"
        make clean
        mv "wikiman-${GITHUB_REF#refs/*/}-1_any.deb" ~/release

    - name: Test installation
      id: test
      run: |
        apt -y install man fzf ripgrep gawk w3m
        dpkg -i ~/release/wikiman-*.deb

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ~/release/wikiman-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  fedora:
    name: Fedora
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:

    - name: Prepare system
      id: prepare
      run: |
        dnf install -y rpm-build make nodejs
        rm -rf ~/rpmbuild ~/release
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
        mkdir -p ~/release
    
    - name: Prepare source package
      id: package
      run: |
        cp ./pkg/rpm/.spec ~/rpmbuild/SPECS/wikiman.spec
        mkdir -p ~/wikiman-${GITHUB_REF#refs/*/}
        cp -r * ~/wikiman-${GITHUB_REF#refs/*/}
        cd ~
        tar czf "${GITHUB_REF#refs/*/}.tar.gz" wikiman-${GITHUB_REF#refs/*/}
        mv "${GITHUB_REF#refs/*/}.tar.gz" ~/rpmbuild/SOURCES

    - name: Build package
      id: build
      run: |
        export PKGVER="${GITHUB_REF#refs/*/}"
        export PKGREL="1"
        rpmbuild -bb ~/rpmbuild/SPECS/wikiman.spec
        mv ~/rpmbuild/RPMS/noarch/wikiman-*.rpm ~/release

    - name: Test installation
      id: test
      run: |
        dnf install -y ~/release/wikiman-*.rpm

    - name: Upload package to release
      id: upload
      uses: svenstaro/upload-release-action@2.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ~/release/wikiman-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true